# Generated by Django 3.0.2 on 2020-01-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
