# Generated by Django 3.0.2 on 2020-02-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Employer', '0004_auto_20200201_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('job_country', models.CharField(default='India', editable=False, max_length=10)),
                ('job_qualification', models.CharField(max_length=30)),
                ('job_quentity', models.IntegerField()),
                ('job_upload_date', models.DateTimeField(auto_now_add=True)),
                ('job_deadline', models.DateField()),
                ('job_bond_time', models.IntegerField()),
                ('job_bond_documents', models.TextField(max_length=40)),
                ('comapny_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employer.Company')),
                ('job_city', models.ManyToManyField(to='Home.City')),
                ('job_states', models.ManyToManyField(to='Home.States')),
            ],
        ),
    ]
