# Generated by Django 3.0.2 on 2020-04-09 16:57

import User.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Enter valid phone number must be entered in the format: '+9999999999'.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('skils', models.TextField(blank=True, max_length=1000, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=User.models.upload_file_path)),
                ('img', models.ImageField(blank=True, null=True, upload_to=User.models.upload_image_path)),
                ('exprerience_type', models.CharField(blank=True, choices=[('E', 'Exprerience'), ('F', 'Fresher')], max_length=1, null=True)),
                ('street_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default='India', editable=False, max_length=10)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.City')),
                ('states', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.States')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
